algoritmo "semnome"
// Função :
// Autor :
// Data : 23/03/2012
// Seção de Declarações 
var
      ini_j, fim_j, h : inteiro
inicio
       escreva("Forneça a hra do inicio do jogo : ")
       leia(ini_j)
       escreva("Forneça a hra de termino do jogo : ")
       leia(fim_j)
       h <- fim_j - ini_J
       se h < 0 entao
           h<- h* -1
       fimse
       escreva("Ojogo tem duraçao ", h, " Hras.")
       
fimalgoritmo
